<?php

namespace ContainerL47IOXz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PpDen1aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ppDen1a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ppDen1a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AuthenticatorController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\FigureController::creationFigure' => ['privates', '.service_locator.sMm5VD0', 'get_ServiceLocator_SMm5VD0Service', true],
            'App\\Controller\\FigureController::editionFigure' => ['privates', '.service_locator.00tNKoW', 'get_ServiceLocator_00tNKoWService', true],
            'App\\Controller\\FigureController::liste' => ['privates', '.service_locator.hIklMnt', 'get_ServiceLocator_HIklMntService', true],
            'App\\Controller\\FigureController::message' => ['privates', '.service_locator.cA2yfBT', 'get_ServiceLocator_CA2yfBTService', true],
            'App\\Controller\\FigureController::print' => ['privates', '.service_locator.sSTSXrh', 'get_ServiceLocator_SSTSXrhService', true],
            'App\\Controller\\FigureController::suppressionFigure' => ['privates', '.service_locator.xDZ9wKP', 'get_ServiceLocator_XDZ9wKPService', true],
            'App\\Controller\\ForgetPasswordController::editPassword' => ['privates', '.service_locator.vjetzzK', 'get_ServiceLocator_VjetzzKService', true],
            'App\\Controller\\ForgetPasswordController::index' => ['privates', '.service_locator.8YhWmfT', 'get_ServiceLocator_8YhWmfTService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.u8tOvUF', 'get_ServiceLocator_U8tOvUFService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.oadqyYf', 'get_ServiceLocator_OadqyYfService', true],
            'App\\Controller\\RegistrationController::verification' => ['privates', '.service_locator.ozsNm6Q', 'get_ServiceLocator_OzsNm6QService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AuthenticatorController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\FigureController:creationFigure' => ['privates', '.service_locator.sMm5VD0', 'get_ServiceLocator_SMm5VD0Service', true],
            'App\\Controller\\FigureController:editionFigure' => ['privates', '.service_locator.00tNKoW', 'get_ServiceLocator_00tNKoWService', true],
            'App\\Controller\\FigureController:liste' => ['privates', '.service_locator.hIklMnt', 'get_ServiceLocator_HIklMntService', true],
            'App\\Controller\\FigureController:message' => ['privates', '.service_locator.cA2yfBT', 'get_ServiceLocator_CA2yfBTService', true],
            'App\\Controller\\FigureController:print' => ['privates', '.service_locator.sSTSXrh', 'get_ServiceLocator_SSTSXrhService', true],
            'App\\Controller\\FigureController:suppressionFigure' => ['privates', '.service_locator.xDZ9wKP', 'get_ServiceLocator_XDZ9wKPService', true],
            'App\\Controller\\ForgetPasswordController:editPassword' => ['privates', '.service_locator.vjetzzK', 'get_ServiceLocator_VjetzzKService', true],
            'App\\Controller\\ForgetPasswordController:index' => ['privates', '.service_locator.8YhWmfT', 'get_ServiceLocator_8YhWmfTService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.u8tOvUF', 'get_ServiceLocator_U8tOvUFService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.oadqyYf', 'get_ServiceLocator_OadqyYfService', true],
            'App\\Controller\\RegistrationController:verification' => ['privates', '.service_locator.ozsNm6Q', 'get_ServiceLocator_OzsNm6QService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AuthenticatorController::login' => '?',
            'App\\Controller\\FigureController::creationFigure' => '?',
            'App\\Controller\\FigureController::editionFigure' => '?',
            'App\\Controller\\FigureController::liste' => '?',
            'App\\Controller\\FigureController::message' => '?',
            'App\\Controller\\FigureController::print' => '?',
            'App\\Controller\\FigureController::suppressionFigure' => '?',
            'App\\Controller\\ForgetPasswordController::editPassword' => '?',
            'App\\Controller\\ForgetPasswordController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verification' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AuthenticatorController:login' => '?',
            'App\\Controller\\FigureController:creationFigure' => '?',
            'App\\Controller\\FigureController:editionFigure' => '?',
            'App\\Controller\\FigureController:liste' => '?',
            'App\\Controller\\FigureController:message' => '?',
            'App\\Controller\\FigureController:print' => '?',
            'App\\Controller\\FigureController:suppressionFigure' => '?',
            'App\\Controller\\ForgetPasswordController:editPassword' => '?',
            'App\\Controller\\ForgetPasswordController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verification' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
