<?php

namespace ContainerL47IOXz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U8tOvUFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u8tOvUF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u8tOvUF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authorizationChecker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
        ], [
            'authorizationChecker' => '?',
        ]);
    }
}
