<?php

namespace ContainerBp0fQjU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendPasswordRecuperationCodeTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SendPasswordRecuperationCodeType' shared autowired service.
     *
     * @return \App\Form\SendPasswordRecuperationCodeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SendPasswordRecuperationCodeType.php';

        return $container->privates['App\\Form\\SendPasswordRecuperationCodeType'] = new \App\Form\SendPasswordRecuperationCodeType();
    }
}
