<?php

namespace ContainerHojcLDE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CA2yfBTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cA2yfBT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cA2yfBT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'figureRepository' => ['privates', 'App\\Repository\\FigureRepository', 'getFigureRepositoryService', true],
            'messageRepo' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
        ], [
            'figureRepository' => 'App\\Repository\\FigureRepository',
            'messageRepo' => 'App\\Repository\\MessageRepository',
        ]);
    }
}
