controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
error404:
    path: /{wildcard}
    controller: App\Controller\ErrorController::error404
    requirements:
        wildcard: ".*"
