<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKRLkFMl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKRLkFMl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKRLkFMl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKRLkFMl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKRLkFMl\App_KernelDevDebugContainer([
    'container.build_hash' => 'KRLkFMl',
    'container.build_id' => 'eaad8aef',
    'container.build_time' => 1685950762,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKRLkFMl');
