<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXpO20rP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXpO20rP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXpO20rP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXpO20rP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXpO20rP\App_KernelDevDebugContainer([
    'container.build_hash' => 'XpO20rP',
    'container.build_id' => '3a05806b',
    'container.build_time' => 1679902351,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXpO20rP');
